name: Build bottles from 'brew request-bottle' trigger.

on: repository_dispatch

jobs:
  bottling:
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    env:
      HOMEBREW_PATCHELF_RB: 1
      HOMEBREW_GIT_NAME: BrewTestBot
      HOMEBREW_GIT_EMAIL: 'homebrew-test-bot@lists.sfconservancy.org'
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - name: Run brew test-bot --only-formulae
        run: |
          mkdir bottles
          cd bottles
          brew test-bot --keep-old --only-formulae ${{github.event.inputs.formula}}

      - name: Output brew test-bot --only-formulae failures
        if: always()
        run: |
          echo formula=${{github.event.client_payload.formula}}
          echo sender=${{github.event.sender.login}}
          echo name=${{github.event.client_payload.name}}
          echo ignore-errors=${{github.event.client_payload.ignore_errors}}
          echo issue=${{github.event.client_payload.issue}}
          echo "::set-output name=repo::$(brew --repo ${{github.repository}})"

      - name: Setup git
        uses: Homebrew/actions/git-user-config@master

      - name: Build bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew update-reset
          brew test-bot \
            --only-formulae \
            --keep-old \
            ${{github.event.client_payload.formula}}

      - name: Copy bottles
        if: always()
        run: |
          cp -a ~/bottles $GITHUB_WORKSPACE

      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: ~/bottles/

      - name: Upload bottles to Bintray
        env:
          HOMEBREW_BINTRAY_USER: linuxbrewtestbot
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        if: success() || github.event.client_payload.ignore_errors
        run: |
          cd ~/bottles
          brew update-reset $(brew --repo ${{github.repository}})
          brew pr-upload \
            --bintray-org=linuxbrew \
            --keep-old \
            --verbose \
            --debug

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        if: success() || github.event.client_payload.ignore_errors
        with:
          directory: ${{ steps.print_details.outputs.repo }}
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}

      - name: Post comment on failure
        if: ${{!success() && github.event.client_payload.issue > 0}}
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          issue: ${{github.event.client_payload.issue}}
          body: ':warning: @${{github.actor}} bottle request for ${{github.event.client_payload.formula}} [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot_body: ':warning: Bottle request for ${{github.event.client_payload.formula}} [failed](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}).'
          bot: BrewTestBot
