name: Wheezy CI
on:
  pull_request:
    paths:
      - "Formula/patchelf.rb"
      - "Formula/binutils.rb"
jobs:
  wheezy_tests:
    if: startsWith(github.event.pull_request.title, 'Merge') == false
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Hack curl version
        run: |
          sed -i 's/HOMEBREW_MINIMUM_CURL_VERSION="7.41.0"/HOMEBREW_MINIMUM_CURL_VERSION="7.25.0"/g' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh
      - name: Setup bottles folder
        run: |
          rm -rf ~/bottles
          mkdir ~/bottles
      - name: Run Docker
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_CURL_PATH: "/usr/bin/curl"
          HOMEBREW_GIT_PATH: "/usr/bin/git"
        run: |
          set -eux
          docker pull homebrew/debian7:latest
          docker run -v /home/linuxbrew:/home/linuxbrew -v ~/bottles:/home/linuxbrew/bottles -u root --env-file <(env | grep 'HOMEBREW\|GITHUB') homebrew/debian7:latest bash -c 'cd /root && brew test-bot --only-formulae --keep-old && cp *.bottle.* /home/linuxbrew/bottles'
      - name: Count bottles
        if: always()
        run: |
          cd ~/bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"
      - name: Move bottles
        if: always() && steps.bottles.outputs.count > 0
        run: mv ~/bottles $GITHUB_WORKSPACE
      - name: Upload bottles
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: ~/bottles
